-module(assignment_2).

% Problem:
%   Each new term in the Fibonacci sequence is generated by adding the previous two terms.
%   By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

-export([
    solution/1
]).


solution(Limit) when is_integer(Limit) ->
    solution(1, 1, Limit, 0).

solution(Previous, Current, Limit, Sum) when (Current =< Limit) andalso (Current rem 2 =:= 0) ->
    solution(Current, Previous + Current, Limit, Sum + Current);

solution(Previous, Current, Limit, Sum) when (Current =< Limit) ->
    solution(Current, Previous + Current, Limit, Sum);

solution(_Previous, _Current, _Limit, Sum) ->
    Sum.